CREATE TABLE IF NOT EXISTS users(id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255));

CREATE TABLE IF NOT EXISTS equations(id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(255), expression VARCHAR(255), answer VARCHAR(255));